# Step1：数据准备

In [1]:
# 导入依赖库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
import warnings
warnings.filterwarnings('ignore')

# 读取数据
data = load_iris()
data_target = data.target
data_feature = pd.DataFrame(data=data.data,columns=data.feature_names)
data_iris = data_feature.copy()
data_iris['target'] = data_target
data_iris


E:\01_Application\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
#安装pandas_profiling:pip install pandas_profiling

import pandas_profiling

pfr = pandas_profiling.ProfileReport(data_iris)
pfr.to_file("./example.html")

Summarize dataset:   0%|          | 0/18 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# Step2：数据探索

In [18]:
# 查看数据整体情况
data_iris.info()
data_iris.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
target               150 non-null int32
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
# 查看数据缺失情况
miss_stat = data_iris.isnull().sum()/data_iris.isnull().count()
# print(data_iris.isnull().sum())
miss_stat

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
target               0.0
dtype: float64

In [22]:
# 查看样本分布情况
pd.Series(data_target).value_counts()


2    50
1    50
0    50
dtype: int64

# Step3：数据预处理

In [ ]:
# 略

# Step4：数据建模

In [39]:
# 二分类
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

iris_feature_part = data_feature.iloc[:100]
iris_target_part = data_target[:100]

# 切分样本
x_train, x_test, y_train, y_test = train_test_split(data_feature, data_target, test_size = 0.2, random_state = 2020)
# x_train, x_test, y_train, y_test = train_test_split(iris_feature_part, iris_target_part, test_size = 0.2, random_state = 2020)

clf = LogisticRegression(random_state=0, solver='lbfgs')
clf = clf.fit(x_train,y_train)

# Step5：模型评估

In [43]:
from sklearn import metrics
from sklearn.metrics import classification_report

y_predict = clf.predict(x_test)
y_predict_proba = clf.predict_proba(x_test)
print(classification_report(y_test,y_predict))
print(y_predict)
print(y_predict_proba)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.70      0.70      0.70        10
           2       0.70      0.70      0.70        10

    accuracy                           0.80        30
   macro avg       0.80      0.80      0.80        30
weighted avg       0.80      0.80      0.80        30

[2 0 1 1 1 1 2 1 0 0 2 1 0 2 2 0 1 1 2 0 0 1 2 0 2 1 2 2 0 0]
[[1.34629657e-04 2.39439258e-01 7.60426112e-01]
 [6.97709974e-01 3.02286872e-01 3.15488105e-06]
 [3.37911357e-02 7.25748311e-01 2.40460553e-01]
 [5.66045749e-03 6.54606650e-01 3.39732893e-01]
 [1.07001604e-02 6.73571458e-01 3.15728381e-01]
 [8.97257212e-04 6.64944383e-01 3.34158360e-01]
 [4.09569374e-04 3.85867863e-01 6.13722567e-01]
 [1.25656705e-01 8.70776967e-01 3.56632803e-03]
 [8.72513103e-01 1.27468517e-01 1.83801129e-05]
 [9.08521668e-01 9.14693374e-02 8.99499116e-06]
 [3.90118125e-04 3.06201906e-01 6.93407976e-01]
 [6.24601292e-03 7.19030139e-

# Step6：模型优化